#-------------------------------
# General Site Settings
title: My Experiences - ParagNair.net
logo: logo.png # You can add own logo.
description: This is my blog where I share my experiences
default-image: bg_fullsize_grass.jpg

#-------------------------------
# Author Settings
author:
  name: Parag Nair
  image: avatar-wiz.png
  say-hello: Hello, I’m <strong>Parag Nair</strong>
  bio: A Full-Stack Cloud Engineer (AWS Certified), a Technologist, solving business problems with a Cloud First <i class="ion-ios-cloud-done"></i> approach.


#-------------------------------
# Contact links
twitter: https://twitter.com/paragnair # Add your Twitter handle
facebook: https://facebook.com/paragnair # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/paragnair # Add your Instagram handle
pinterest: https://pinterest.com/paragnair # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
